server:
  http:
    enable: true
    addr: 0.0.0.0:8080
    timeout: 1s
    enable_metric: true
    enable_trace: true
    auth_white_pathlist: ["/v1/user/wx/login","/v1/user/wx/reg/fast"]
  grpc:
    enable: false
    addr: 0.0.0.0:8081
    timeout: 1s
    enable_metric: true
    enable_trace: true
metric:
  enable: true
  addr: 0.0.0.0:8002

service:
  test_wx_code: abcd
  key_pair:
    public_key: "./public_key.pem"
    private_key: "./private_key.pem"

data:
  rds:
    host: localhost
    port: 5432
    user: "dev"
    password: "123456"
    dbname: "dev_db"
    sslmode: disable
