server:
  http:
    enable: true
    addr: 0.0.0.0:8080
    timeout: 1s
    enable_metric: true
    enable_trace: true
  grpc:
    enable: false
    addr: 0.0.0.0:8081
    timeout: 1s
    enable_metric: true
    enable_trace: true
metric:
  enable: true
  addr: 0.0.0.0:8002

service:

data:
  rds:
    host: localhost
    port: 5432
    user: "dev"
    password: "123456"
    dbname: "dev_db"
    sslmode: disable