server:
  http:
    enable: true
    addr: 0.0.0.0:8080
    timeout: 1s
    enable_metric: true
    enable_trace: true
  grpc:
    enable: false
    addr: 0.0.0.0:8081
    timeout: 1s
    enable_metric: true
    enable_trace: true
metric:
  enable: true
  addr: 0.0.0.0:8002
runner:
  model_pipelines:
    code_gen:
      model_inference:
        kind: triton
        spec:
          grpc_endpoint: code_gen_triton:8083
          timeout: 1s
      pre_process:
        kind: default
        spec:
          grpc_endpoint: gpt2_tokenizer:8084
          timeout: 1s
      post_process:
        kind: default
        spec:
          grpc_endpoint: gpt2_tokenizer:8084
          timeout: 1s
