server:
  http:
    enable: true
    addr: 0.0.0.0:8080
    timeout: 1s
    enable_metric: false
    enable_trace: false
    enable_swagger: true
    auth_white_pathlist: ["/v1/user/wx/login", "/v1/user/wx/reg/fast"]
  grpc:
    enable: false
    addr: 0.0.0.0:8081
    timeout: 1s
    enable_metric: true
    enable_trace: true
metric:
  enable: true
  addr: 0.0.0.0:8002

service:
  test_wx_code: abcd
  key_pair:
    public_key: "./configs/public_key.pem"
    private_key: "./configs/private_key.pem"

data:
  rds:
    host: localhost
    port: 5432
    user: "dev"
    password: "12345678"
    db_name: "dev_db"
    ssl_mode: disable
  fds:
    endpoint: http://127.0.0.1:9000
    access_key: dev
    secret_key: 12345678
  map_data:
    endpoint: https://restapi.amap.com/v3
    key: YOUR_AMAP_KEY
