// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.14.0
// source: base-service.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BaseService_WeChatLogin_FullMethodName                = "/base_service.BaseService/WeChatLogin"
	BaseService_WeChatRegisterWithLogin_FullMethodName    = "/base_service.BaseService/WeChatRegisterWithLogin"
	BaseService_QueryFootprintByCoordinate_FullMethodName = "/base_service.BaseService/QueryFootprintByCoordinate"
	BaseService_QueryFootprintByTime_FullMethodName       = "/base_service.BaseService/QueryFootprintByTime"
	BaseService_CreateFootprint_FullMethodName            = "/base_service.BaseService/CreateFootprint"
	BaseService_DeleteFootprint_FullMethodName            = "/base_service.BaseService/DeleteFootprint"
	BaseService_UpdateFootprint_FullMethodName            = "/base_service.BaseService/UpdateFootprint"
)

// BaseServiceClient is the client API for BaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// 通用业务服务接口定义.
// [EN] API of Service.
type BaseServiceClient interface {
	// 微信小程序登录接口
	WeChatLogin(ctx context.Context, in *WeChatLoginReq, opts ...grpc.CallOption) (*WeChatLoginResp, error)
	// 微信小程序登录注册接口定义
	WeChatRegisterWithLogin(ctx context.Context, in *RegisterWithLoginReq, opts ...grpc.CallOption) (*RegisterWithLoginResp, error)
	// 坐标查询足迹点
	QueryFootprintByCoordinate(ctx context.Context, in *QueryFootprintByCoordinateReq, opts ...grpc.CallOption) (*QueryFootprintByCoordinateResp, error)
	// 查询足迹点
	QueryFootprintByTime(ctx context.Context, in *QueryFootprintByTimeReq, opts ...grpc.CallOption) (*QueryFootprintByTimeResp, error)
	// 创建足迹点
	CreateFootprint(ctx context.Context, in *CreateFootprintReq, opts ...grpc.CallOption) (*CreateFootprintResp, error)
	// 删除足迹点
	DeleteFootprint(ctx context.Context, in *DeleteFootprintReq, opts ...grpc.CallOption) (*DeleteFootprintResp, error)
	// 更新足迹点
	UpdateFootprint(ctx context.Context, in *UpdateFootprintReq, opts ...grpc.CallOption) (*UpdateFootprintResp, error)
}

type baseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBaseServiceClient(cc grpc.ClientConnInterface) BaseServiceClient {
	return &baseServiceClient{cc}
}

func (c *baseServiceClient) WeChatLogin(ctx context.Context, in *WeChatLoginReq, opts ...grpc.CallOption) (*WeChatLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WeChatLoginResp)
	err := c.cc.Invoke(ctx, BaseService_WeChatLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) WeChatRegisterWithLogin(ctx context.Context, in *RegisterWithLoginReq, opts ...grpc.CallOption) (*RegisterWithLoginResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterWithLoginResp)
	err := c.cc.Invoke(ctx, BaseService_WeChatRegisterWithLogin_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryFootprintByCoordinate(ctx context.Context, in *QueryFootprintByCoordinateReq, opts ...grpc.CallOption) (*QueryFootprintByCoordinateResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFootprintByCoordinateResp)
	err := c.cc.Invoke(ctx, BaseService_QueryFootprintByCoordinate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) QueryFootprintByTime(ctx context.Context, in *QueryFootprintByTimeReq, opts ...grpc.CallOption) (*QueryFootprintByTimeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryFootprintByTimeResp)
	err := c.cc.Invoke(ctx, BaseService_QueryFootprintByTime_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) CreateFootprint(ctx context.Context, in *CreateFootprintReq, opts ...grpc.CallOption) (*CreateFootprintResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFootprintResp)
	err := c.cc.Invoke(ctx, BaseService_CreateFootprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) DeleteFootprint(ctx context.Context, in *DeleteFootprintReq, opts ...grpc.CallOption) (*DeleteFootprintResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFootprintResp)
	err := c.cc.Invoke(ctx, BaseService_DeleteFootprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *baseServiceClient) UpdateFootprint(ctx context.Context, in *UpdateFootprintReq, opts ...grpc.CallOption) (*UpdateFootprintResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateFootprintResp)
	err := c.cc.Invoke(ctx, BaseService_UpdateFootprint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BaseServiceServer is the server API for BaseService service.
// All implementations must embed UnimplementedBaseServiceServer
// for forward compatibility.
//
// 通用业务服务接口定义.
// [EN] API of Service.
type BaseServiceServer interface {
	// 微信小程序登录接口
	WeChatLogin(context.Context, *WeChatLoginReq) (*WeChatLoginResp, error)
	// 微信小程序登录注册接口定义
	WeChatRegisterWithLogin(context.Context, *RegisterWithLoginReq) (*RegisterWithLoginResp, error)
	// 坐标查询足迹点
	QueryFootprintByCoordinate(context.Context, *QueryFootprintByCoordinateReq) (*QueryFootprintByCoordinateResp, error)
	// 查询足迹点
	QueryFootprintByTime(context.Context, *QueryFootprintByTimeReq) (*QueryFootprintByTimeResp, error)
	// 创建足迹点
	CreateFootprint(context.Context, *CreateFootprintReq) (*CreateFootprintResp, error)
	// 删除足迹点
	DeleteFootprint(context.Context, *DeleteFootprintReq) (*DeleteFootprintResp, error)
	// 更新足迹点
	UpdateFootprint(context.Context, *UpdateFootprintReq) (*UpdateFootprintResp, error)
	mustEmbedUnimplementedBaseServiceServer()
}

// UnimplementedBaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBaseServiceServer struct{}

func (UnimplementedBaseServiceServer) WeChatLogin(context.Context, *WeChatLoginReq) (*WeChatLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WeChatLogin not implemented")
}
func (UnimplementedBaseServiceServer) WeChatRegisterWithLogin(context.Context, *RegisterWithLoginReq) (*RegisterWithLoginResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WeChatRegisterWithLogin not implemented")
}
func (UnimplementedBaseServiceServer) QueryFootprintByCoordinate(context.Context, *QueryFootprintByCoordinateReq) (*QueryFootprintByCoordinateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFootprintByCoordinate not implemented")
}
func (UnimplementedBaseServiceServer) QueryFootprintByTime(context.Context, *QueryFootprintByTimeReq) (*QueryFootprintByTimeResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryFootprintByTime not implemented")
}
func (UnimplementedBaseServiceServer) CreateFootprint(context.Context, *CreateFootprintReq) (*CreateFootprintResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFootprint not implemented")
}
func (UnimplementedBaseServiceServer) DeleteFootprint(context.Context, *DeleteFootprintReq) (*DeleteFootprintResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFootprint not implemented")
}
func (UnimplementedBaseServiceServer) UpdateFootprint(context.Context, *UpdateFootprintReq) (*UpdateFootprintResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateFootprint not implemented")
}
func (UnimplementedBaseServiceServer) mustEmbedUnimplementedBaseServiceServer() {}
func (UnimplementedBaseServiceServer) testEmbeddedByValue()                     {}

// UnsafeBaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BaseServiceServer will
// result in compilation errors.
type UnsafeBaseServiceServer interface {
	mustEmbedUnimplementedBaseServiceServer()
}

func RegisterBaseServiceServer(s grpc.ServiceRegistrar, srv BaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedBaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BaseService_ServiceDesc, srv)
}

func _BaseService_WeChatLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WeChatLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).WeChatLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_WeChatLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).WeChatLogin(ctx, req.(*WeChatLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_WeChatRegisterWithLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterWithLoginReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).WeChatRegisterWithLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_WeChatRegisterWithLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).WeChatRegisterWithLogin(ctx, req.(*RegisterWithLoginReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryFootprintByCoordinate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFootprintByCoordinateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryFootprintByCoordinate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryFootprintByCoordinate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryFootprintByCoordinate(ctx, req.(*QueryFootprintByCoordinateReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_QueryFootprintByTime_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryFootprintByTimeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).QueryFootprintByTime(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_QueryFootprintByTime_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).QueryFootprintByTime(ctx, req.(*QueryFootprintByTimeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_CreateFootprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFootprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).CreateFootprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_CreateFootprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).CreateFootprint(ctx, req.(*CreateFootprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_DeleteFootprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFootprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).DeleteFootprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_DeleteFootprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).DeleteFootprint(ctx, req.(*DeleteFootprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _BaseService_UpdateFootprint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateFootprintReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BaseServiceServer).UpdateFootprint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BaseService_UpdateFootprint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BaseServiceServer).UpdateFootprint(ctx, req.(*UpdateFootprintReq))
	}
	return interceptor(ctx, in, info, handler)
}

// BaseService_ServiceDesc is the grpc.ServiceDesc for BaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "base_service.BaseService",
	HandlerType: (*BaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "WeChatLogin",
			Handler:    _BaseService_WeChatLogin_Handler,
		},
		{
			MethodName: "WeChatRegisterWithLogin",
			Handler:    _BaseService_WeChatRegisterWithLogin_Handler,
		},
		{
			MethodName: "QueryFootprintByCoordinate",
			Handler:    _BaseService_QueryFootprintByCoordinate_Handler,
		},
		{
			MethodName: "QueryFootprintByTime",
			Handler:    _BaseService_QueryFootprintByTime_Handler,
		},
		{
			MethodName: "CreateFootprint",
			Handler:    _BaseService_CreateFootprint_Handler,
		},
		{
			MethodName: "DeleteFootprint",
			Handler:    _BaseService_DeleteFootprint_Handler,
		},
		{
			MethodName: "UpdateFootprint",
			Handler:    _BaseService_UpdateFootprint_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "base-service.proto",
}
